version: '3.8'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
  backend:
    build: ./backend
    command:
      - ./bin/rails
      - server
      - -b
      - 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/rails
      - backend_volume:/usr/local/bundle
    environment:
      - RAILS_ENV=development
    depends_on:
      - db
volumes:
  db_volume:
  backend_volume:
